SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `image`;
DROP TABLE IF EXISTS `location`;
DROP TABLE IF EXISTS `user_location`;
SET GLOBAL FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `user` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`username` VARCHAR(355) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`created` DATE NOT NULL,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);


CREATE TABLE IF NOT EXISTS  `image` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `location_id` INT(11) UNSIGNED NOT NULL,
  `image_id` VARCHAR(255) NOT NULL,
  `landmark` TEXT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `tags` TEXT NOT NULL,
  `date_taken` DATETIME DEFAULT NULL,
  `description` TEXT,
  `url` VARCHAR(255) NOT NULL,
	`created` DATE NOT NULL,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);


CREATE TABLE IF NOT EXISTS  `location` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(155) NOT NULL,
  `created` DATE NOT NULL,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);


CREATE TABLE IF NOT EXISTS  `user_location` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `location_id` INT(11) UNSIGNED DEFAULT NULL,
  `created` DATE NOT NULL,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
	CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES `user`(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT FK_location_id FOREIGN KEY (location_id) REFERENCES `location`(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
